### ISSUE TITLE
GetAssetsByCreator is returning random assets for random pubkeys.

### ISSUE THREAD

**Issue by ethyi** [metaplex-foundation/digital-asset-rpc-infrastructure#51] opened 2023-04-05 18:10 UTC
Inputting a random pubkey into getAssetsByCreator will return a random set of data. Data just so happens to be alphanumerically sorted, perhaps for the entire DB.
```
{
    "jsonrpc": "2.0",
    "id": "0",
    "method": "get_assets_by_creator",
    "params": {
        "page": 1,
        "creatorVerified": true,
        "creatorAddress": "1234abcd8htfC7YEXKNEfkpuogUUQDDTLgjGWxxv48a",
        "limit": 1000
    }
}
```

**Comment by brianlong** [comment] 2023-04-05 18:55
🤦🏻

**Comment by NicolasPennie** [comment] 2023-04-06 01:29
FYI, the proper query would have "verifiedOnly" instead of "creatorVerified". 

When "verifiedOnly" = true, it works as intended.
When "verifiedOnly" = false, every single non-verified NFT is returned.

**Comment by NicolasPennie** [comment] 2023-04-06 02:29
Fixed via https://github.com/metaplex-foundation/digital-asset-rpc-infrastructure/issues/51

Unfortunately there is still a problem with regular NFTs: https://github.com/metaplex-foundation/digital-asset-rpc-infrastructure/issues/53

**Closed** 2023-04-07 13:49 UTC
